In [4]:
import numpy as np

a=np.array([1,2,3,4,5])
print(a)
print(type(a))


[1 2 3 4 5]
<class 'numpy.ndarray'>


In [6]:
b=np.array([[1,2,3,4,5],[6,7,8,9,10]])
type(b)

numpy.ndarray

In [7]:
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [8]:
np.shape(b)

(2, 5)

In [9]:
c=np.linspace(0,1,10)
print(c)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [12]:
d=np.array([10,20,30,40,50])
d

array([10, 20, 30, 40, 50])

In [13]:
np.min(d)

np.int64(10)

In [14]:
np.max(d)

np.int64(50)

In [15]:
np.median(d)

np.float64(30.0)

In [16]:
np.mean(d)

np.float64(30.0)

In [17]:
#generate a random array 

In [18]:
import numpy as np

In [20]:
E=np.random.randint(1,101,10)
print("Original E:")
print(E)
print("sorted E:")
print(E)

Original E:
[80 53 78 51  2 24 80 49 91 92]
sorted E:
[80 53 78 51  2 24 80 49 91 92]


In [21]:
np.min(E)

np.int32(2)

In [22]:
np.max(E)

np.int32(92)

In [23]:
np.mean(E)

np.float64(60.0)

In [24]:
np.std(E)

np.float64(28.319604517012593)

In [25]:
s=np.arange(1,13)
s

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [26]:
s1=s.reshape(3,4)
s1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [4]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr+5)
print(arr*2)

[ 6  7  8  9 10]
[ 2  4  6  8 10]


In [5]:
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a+b)
print(a-b)
print(a*b)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]


In [6]:
np.dot(a,b)

np.int64(32)

In [7]:
import numpy as np

In [8]:
c=np.array([10,20,30,40,50,60,70,80])
print(c[:3])

[10 20 30]


In [9]:
print(c[-3:])

[60 70 80]


In [11]:
print(c[2:6])

[30 40 50 60]
